- META
It is working without that because findlib has a fixup/hack for that. It adds to all the library a dependency to threads when mt is used. In dune there is no hack, so users have strange error if they write `(libraries lablgtk threads)` or `(libraries lablgtk)` instead of `(libraries threads lablgtk)`.
> Add requires threads in case of `mt` predicate

- src/gToolbox.ml
- src/gToolbox.mli
This extends PR #12 as proposed [here](https://github.com/garrigue/lablgtk/pull/12#issuecomment-439335466).
We simplify the API by making `destroy_with_parent` true by default whenever `parent` is given. We add option `parent` to `tree_selection_dialog`, `input_text` and `input_string`.
> Extended supports for declaring boxes transient for a parent

- src/gAssistant.mli
- src/gWindow.mli
- src/gtkBase.props
These properties were deprecated in GTK 2.22 and do not exist anymore
in GTK3. A lablgtk application that tries to use them will crash with
an obscure error message. This was the case for Why3.
> Remove properties allow-grow and allow-shrink from GtkWindow.

- src/gtkMenu.ml
There does not seem to be anything wrong with the function and it is
used by Why3.
> Restore GtkMenu.MenuItem.separator_create.

- src/gTree.mli
- src/gtkTree.props
By default, the last column of a tree view gets all the extra space. This
property makes it possible to give that space to some other columns.
It is available since GTK 2.4 and is still present in GTK 3.
> Support property "expand" of GtkTreeViewColumn.

- src/gEdit.mli
- src/gtkEdit.props
It is available since GTK 3.2.
> Support property "placeholder-text" of GtkEntry.

- src/gObj.ml
- src/gObj.mli
Hi @garrigue, CoqIDE was also using one instance of `destroy` from `misc_signals` (formerly via `gtkobj_signals_impl`). I'm not very comfortable with the organization of signals but it seems that this signal is now directly provided as a `Widget` signal and could be exported. This is what this PR is doing for lablgtk3.
> Exporting destroy in misc signals

- .gitignore
- .travis.yml
- CHANGES
- Makefile.travis
- README.dune.md
- applications/browser/dune
- applications/camlirc/dune
- azure-pipelines.yml
- dune-project
- examples/dune
- examples/image.ml
- lablgtk3-sourceview3.opam
- lablgtk3.opam
- src/dune
- src/dune-enum.sexp
- src/dune-prop.sexp
- src/dune_config.ml
- src/introspection/Gtk-3.0.gir
We add preliminary support for building with Dune to lablgtk3; it
seems to work well and does provide some advantages:
- compositional build with other developments, for example CoqIDE,
- it allows for an easier layout / library reorganization if wished,
- automatic management of install targets, opam install file, META, stubs,
- automatic generation of documentation with `odoc`.
Release / usage instructions are placed in `README.dune.md`.
The dune files use an "explicit" style. While a bit more
verbose than other setup, it is very easy to understand.
Note we pass `-Wno-deprecated-declarations` to the C compiler as to
avoid a super-verbose build. We also disable a few OCaml warnings.
One strong motivation to do this PR is to help the GTK 3 porting
effort and this provides a seamless …
> [build] Add support for building and releasing with Dune.

- src/dune
This seems to be a noop and it is not needed anymore after
d086ec7576758f136be21397ee61a793825f666b
> [build] Remove failed flag workaround.

- .travis.yml
- src/dune
- src/propcc.ml
- src/propcc.ml4
- src/varcc.ml
- src/varcc.ml4
We do a warnings cleanup on the way.
The camlp4 rule has to be a bit special to ensure the loading of
`pr_o` as for promotion to work better; by default, `camlp4o` will use
Camlp4AutoPrinter which does:
```ocaml
if Unix.isatty Unix.stdout then
enable_ocaml_printer ()
else
enable_dump_ocaml_ast_printer ();
```
which turns out to be very inconvenient.
> [build] Teach dune about generation from ml4 files.

- Makefile.travis
- examples/dune
- examples/fixed_editor.ml
- examples/fixpoint.ml
This is ported from the GTK2 branch, so it is not enough for GTK3.
Note the additions of the `-linkall` flag. As far as I can see this is
necessary in order to avoid:
```
Fatal error: exception Failure("Gobject.unsafe_create : type GtkFrame is not yet defined")
```
etc...
> [examples] Fix a few examples.

- src/ml_pango.c
- src/pango.ml
- src/pango_tags.var
Additions to Pango module:
```ocaml
module Tags : sig
....
type alignment = [ `LEFT | `CENTER | `RIGHT ]
end
module Layout : sig
....
val get_baseline   : layout -> int
val get_line_count : layout -> int
val is_wrapped     : layout -> bool
val is_ellipsized  : layout -> bool
val get_alignment  : layout -> alignment
val set_alignment  : layout -> alignment -> unit
end
```
> Add additional Pango.Layout functions

- src/gdk.mli
For some reason the PR I submitted (#60) did not contain the mli change.
> Fixup mli for Gdk.Window.get_origin.

- src/ml_gtksourceview3.c
It was a typo, the expected type was not matching with what was written down.
> Fix GtkSourceView dynamic type checking.

- CHANGES.md
- examples/cairo_demo.ml
- examples/dune
- examples/pango1.ml
- examples/pango2.ml
- src/dune
Fixes #71 ; the support for `pango_cairo` was added in #33, however
Dune support was done for a branch without that modules, thus they were
not included in the build.
We just add the pango_cairo modules and stubs to the dune build.
> [dune] Build support for pango_cairo

- .travis.yml
As part of global effort to bring 4.08 support in the most common packages.
> Add OCaml 4.08 in Travis CI

- src/ml_gtktree.c
- src/wrappers.h
* Fix the `wrappers.h` part of #92 by making the re-declaration of `young_start` and `young_end` conditional on ocaml version older than 4.10.
* Replace `caml_young_{start,end}` by `young_*` in `ml_gtktree.c` to work around bug in pre-release 4.10.
> Remove declaration of young_start for ocaml 4.10

- .travis.yml
Brew recipe for OPAM turns out to be problematic [certificate
problems] so we install directly from the upstream binary package.
> [travis] Fix OSX build

- .travis.yml
- CHANGES.md
- dune-project
- lablgtk3-gtkspell3.opam
- lablgtk3-sourceview3.opam
- lablgtk3.opam
- tools/dune_config.ml
We use the new configurator API which does provide better error
messages and avoids some warnings during build. This means we have to
bump to dune 1.8.0 but that should not be a problem these days.
We also correct the opam files as to remove the `build` dune flag [as
per upstream policy], and require a strict matching on the version
field for depending packages [safer and few downsides]
> [build] Use newer configurator API, correct build-deps

- .travis.yml
- tools/dune
- tools/gtkdoc.ml
We enable compilation of gtkdoc and test it. In the future we could
add an ocamldoc rule to resurrect the documentation build with Dune.
It would maybe be worth porting this to `odoc`.
> [gtkdoc] Test gtkdoc compilation

- CHANGES.md
- src/ml_gdk.c
- src/ml_gdk.h
GCC has defaulted to -fcommon for many years.  GCC 10 is changing the default to -fno-common, which has led to lablgtk failing to build because every compilation unit that includes ml_gdk.h has its own variable named `ml_table_extension_events`.  This commit ensures that there is exactly one definition of that variable.
> Fix the build with -fno-common.

- src/ml_glib.c
- src/ml_gtk.c
- src/ml_gtktree.c
- src/wrappers.h
This PR makes it possible for lablgtk3 to be compiled with ocaml-multicore. However there are still a few warnings here and there and the example program I've tried segfaults, .. Though it's better than nothing and the changes are still relevant in recent versions of OCaml anyway as it simply uses the caml namespace instead of the deprecated functions/values.
> Add partial support for OCaml 5.00

- src/ml_glib.c
- src/ml_gtk.c
- src/ml_gtktree.c
- src/wrappers.h
Backports https://github.com/garrigue/lablgtk/pull/129 to the `master` branch
> Backports #129 to lablgtk2

- examples/glade/dune
- lablgtk3.opam
I'm attempting to get lablgtk3 to build under ocaml-ci. Here are some fixes that seem to help a bit:
- Add `{dev}` dependency on `camlp5`. Camlp5 is mentioned in the README as needed for local development, but wasn't in the opam file.
-  Add `{dev}` dependency on `ocamlfind`. This seems to be necessary in order for dune to find the `ocamldoc` library (which is currently bundled with OCaml). This is needed to build `gtkdoc`, which doesn't seem to be used for anything, so it's only needed for dev or CI builds (which probably use `dune build @check`).
- The glade rules needed to list the ui files as dependencies.
Even with this, there are still a lot of errors. e.g.
```
File "examples/fixed_editor.ml", line 95, characters 28-45:
95 |       let (width, height) = Drawable.get_size w in …
```
> Some build fixes

- src/ml_glib.c
- src/ml_glib.h
- src/ml_gobject.c
Fixes #141
See also https://github.com/verifast/verifast/issues/252 . With this patch, the VeriFast IDE works correctly and I can no longer get it to crash.
> Leave blocking section on callback while polling

- examples/css.ml
- examples/dune
- src/gObj.ml
- src/gObj.mli
- src/gtk.ml
- src/gtkBase.ml
- src/gtkData.ml
- src/ml_gtk.c
- src/ml_gtk.h
My goal is to address https://github.com/coq/coq/issues/12779
> Add bindings for applying CSS from a string

- examples/tree.ml
- src/gTree.ml
- src/gTree.mli
- src/gtkTree.props
- tools/propcc.ml
- tools/propcc.ml4
Allow text wrapping in cells in tree view.
Description of wrap-width:
https://docs.gtk.org/gtk3/property.CellRendererText.wrap-width.html
I can't figure out how to get wrap-mode to work:
https://docs.gtk.org/gtk3/property.CellRendererText.wrap-mode.html
> Add WRAP_WIDTH, WRAP_MODE tags to cell_properties_text, supported since gtk 2.8

- CHANGES
- src/Makefile
- src/check_externals.ml
- src/gpointer.ml
- src/gpointer.mli
- src/gtkList.ml
- src/gtkMain.ml
- src/ml_gtklist.c
- src/propcc.ml
- src/varcc.ml
- src/varcc.ml4
- src/wrappers.c
- src/wrappers.h
The `lookup_info` structures generated by `varcc` were returned as raw pointers to ocaml, which caused failures in multicore.
This fixes that by wrapping them, and returning them inside an allocated tuple.
(Same as #144, but for lablgtk2 this time)
> Remove naked pointers and Obj.truncate for compatibility with 5.00 [lablgtk2]

- CHANGES.md
- src-unsupported/ml_gtklist.c
- src/gpointer.ml
- src/gpointer.mli
- src/gtkMain.ml
- src/wrappers.c
- src/wrappers.h
- tools/propcc.ml
- tools/varcc.ml
- tools/varcc.ml4
The `lookup_info` structures generated by `varcc` were returned as raw pointers to ocaml, which caused failures in multicore.
This fixes that by wrapping them, and returning them inside an allocated tuple.
> Remove naked pointers and Obj.truncate for compatibility with 5.00
